inference:
  inference: False
  max_new_tokens: 64
  prompt: "merhaba"
  checkpoint: None

train:
  model: "decoder"
  world_size: 1
  force: False
  model_info: True
  training_type: pre-train 
  epoch: 5
  lr: 1e-4
  eval_steps: 10
  eval_sample: 1

data:
  hf_tokenizer: "vngrs-ai/Kumru-2B"
  pretraining_hf_data: "canbingol/vngrs-web-corpus-500k"
  it_hf_data: "canbingol/turkish_instructions"
  text_column_name: "text"
  token_path: "./data/pretrain/default_tokenizer"

  tokens_chunks_size: 25000000
  test_split: 0.05
  token_dtype: np.uint16
  vocab_size: 50176
  batch_size: 1

  shuffle: False
  drop_last: True
  num_workers: 0
  pin_memory: True
  max_seq_len: 512
  pad_token: 0
  
