# -----------------------------
# Inference configuration
# -----------------------------
model: "gpt2"
tokenizer_path: "vngrs-ai/Kumru-2B"
prompt: "adam bir g√ºn"
checkpoint: "./output/gpt2/GPT2_best_model_data500k_loss4.3.pt"
