hub:
  push_to_hub: True
  repo_name: canbingol/my-awesome-model

train:
  model: "decoder"
  attn: "sdpa"
  world_size: 1
  force: False
  model_info: True
  training_type: "pre-train"
  epoch: 1
  lr: 1e-4
  eval_steps: 10
  eval_sample: 1
  training_steps: 1000000
  
data:
  hf_tokenizer: "vngrs-ai/Kumru-2B"
  pretraining_hf_data: "canbingol/vngrs-web-corpus-500k"
  it_hf_data: "canbingol/turkish_instructions"
  text_column_name: "text"
  token_path: "./data/pretrain/default_tokenizer"

  tokens_chunks_size: 25000000
  test_split: 0.05
  token_dtype: np.uint16
  batch_size: 1

  shuffle: False
  drop_last: True
  num_workers: 0
  pin_memory: True
  max_seq_len: 512
  pad_token: 0
  
model:
  attention_bias: False
  attention_dropout: 0.0
  bos_token_id: 151643
  eos_token_id: 151645

  intermediate_size: 3072
  hidden_act: "silu"

  head_dim: 32
  hidden_size: 1024
  num_attention_heads: 16
  num_hidden_layers: 1
  num_key_value_heads: 8
  vocab_size: 50176
  max_position_embeddings: 40960    

  rms_norm_eps: 1e-6
  rope_theta: 1000000

  use_cache: True
  attn_type: "eager"
  torch_dtype: "bfloat16"